version: "1.0"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    env_file:
      - ./server/.env

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 5174:5174
    env_file:
      - ./client/.env
    depends_on:
      - server
